// GENERATED by scripts/build-images.mjs — do not edit by hand.
// Re-run: node scripts/build-images.mjs

export type ImageSlot =
  | 'home-hero-dry-field'
  | 'home-before-drought-maize'
  | 'home-after-healthy-maize'
  | 'home-essay-farmer'
  | 'home-essay-soil'
  | 'home-essay-seed'
  | 'home-essay-harvest'
  | 'home-impact-market'
  | 'home-cta-farmland'
  | 'advisor-hero-seedlings'
  | 'advisor-seed-closeup'
  | 'advisor-trial-plots'
  | 'advisor-millet-field'
  | 'advisor-planting'
  | 'climate-hero-drought'
  | 'climate-rain-clouds'
  | 'climate-irrigation'
  | 'climate-sahel'
  | 'climate-dry-riverbed'
  | 'surveillance-hero-pest'
  | 'surveillance-leaf-disease'
  | 'surveillance-scouting'
  | 'surveillance-phone-field'
  | 'surveillance-cassava'
  | 'agronomist-hero-extension'
  | 'agronomist-training'
  | 'agronomist-soil-test'
  | 'agronomist-field-demo'
  | 'about-mosaic-1'
  | 'about-mosaic-2'
  | 'about-mosaic-3'
  | 'about-mosaic-4'
  | 'blog-drought-varieties'
  | 'blog-soil-health'
  | 'blog-planting-calendar'
  | 'blog-armyworm'
  | 'blog-seed-systems'
  | 'blog-cowpea-nitrogen'
  | 'contact-support';

export interface ManagedImage {
  src: string;
  alt: string;
  width: number;
  height: number;
  /** Attribution string to render when the licence requires it. */
  credit: string | null;
  creditUrl: string | null;
  licence: string | null;
}

export const images: Record<ImageSlot, ManagedImage> = {
  'home-hero-dry-field': {
    src: '/images/cropx/home-hero-dry-field.jpg',
    alt: 'Parched farmland under a hazy sky at the end of a failed rainy season',
    width: 1024,
    height: 683,
    credit: 'TREEAID (CC BY)',
    creditUrl: 'https://www.flickr.com/photos/53871588@N05/5630241115',
    licence: 'CC BY',
  },
  'home-before-drought-maize': {
    src: '/images/cropx/home-before-drought-maize.jpg',
    alt: 'Maize plants stunted and browning after a prolonged mid season dry spell',
    width: 2000,
    height: 1328,
    credit: 'Neil Palmer / CIAT (CC BY-SA)',
    creditUrl: 'https://commons.wikimedia.org/wiki/File:NP_Ghana_64_copy_(5209284418).jpg',
    licence: 'CC BY-SA',
  },
  'home-after-healthy-maize': {
    src: '/images/cropx/home-after-healthy-maize.jpg',
    alt: 'A dense stand of healthy green maize reaching well above waist height',
    width: 2000,
    height: 1321,
    credit: 'Jernej Furman (CC BY)',
    creditUrl: 'https://commons.wikimedia.org/wiki/File:Green_corn_rows_and_waves_of_the_agricultural_fields_(52340666758).jpg',
    licence: 'CC BY',
  },
  'home-essay-farmer': {
    src: '/images/cropx/image_farm_description.jpg',
    alt: 'A farmer resting with a hoe beside tall green maize',
    width: 640,
    height: 960,
    credit: null,
    creditUrl: null,
    licence: null,
  },
  'home-essay-soil': {
    src: '/images/cropx/home-essay-soil.jpg',
    alt: 'Hands taking a soil sample from a freshly dug pit',
    width: 1024,
    height: 1024,
    credit: 'Stas Wilf (CC BY)',
    creditUrl: 'https://www.flickr.com/photos/38629276@N06/5973210179',
    licence: 'CC BY',
  },
  'home-essay-seed': {
    src: '/images/cropx/home-essay-seed.jpg',
    alt: 'A handful of cereal seed held up close to the camera',
    width: 1024,
    height: 1024,
    credit: 'jared (CC BY)',
    creditUrl: 'https://www.flickr.com/photos/35468148654@N01/4794928671',
    licence: 'CC BY',
  },
  'home-essay-harvest': {
    src: '/images/cropx/home-maize-harvest.jpg',
    alt: 'CropX cofounder Idokoh Divine Ojochide holding a freshly harvested ear of maize in a cornfield',
    width: 2000,
    height: 2000,
    credit: null,
    creditUrl: null,
    licence: null,
  },
  'home-impact-market': {
    src: '/images/cropx/home-impact-market.jpg',
    alt: 'Sacks of grain stacked at an open-air market stall',
    width: 1024,
    height: 684,
    credit: 'Rod Waddington (CC BY-SA)',
    creditUrl: 'https://www.flickr.com/photos/64607715@N05/14503228657',
    licence: 'CC BY-SA',
  },
  'home-cta-farmland': {
    src: '/images/cropx/home-cta-farmland.jpg',
    alt: 'Cultivated farmland stretching to the horizon in low evening light',
    width: 1024,
    height: 649,
    credit: 'H Dragon (CC BY)',
    creditUrl: 'https://www.flickr.com/photos/81427512@N00/2655972761',
    licence: 'CC BY',
  },
  'advisor-hero-seedlings': {
    src: '/images/cropx/advisor-hero-seedlings.jpg',
    alt: 'Rows of young seedlings raised in a nursery before transplanting',
    width: 1024,
    height: 768,
    credit: 'TREEAID (CC BY)',
    creditUrl: 'https://www.flickr.com/photos/53871588@N05/5384141846',
    licence: 'CC BY',
  },
  'advisor-seed-closeup': {
    src: '/images/cropx/advisor-seed-closeup.jpg',
    alt: 'A close view of cereal grain showing seed size and colour',
    width: 1400,
    height: 1400,
    credit: null,
    creditUrl: 'https://commons.wikimedia.org/w/index.php?curid=175333808',
    licence: 'CC0 1.0',
  },
  'advisor-trial-plots': {
    src: '/images/cropx/advisor-trial-plots.jpg',
    alt: 'Adjacent research plots used to compare crop varieties side by side',
    width: 1023,
    height: 682,
    credit: '{ pranav } (CC BY)',
    creditUrl: 'https://www.flickr.com/photos/29220600@N08/3512075728',
    licence: 'CC BY',
  },
  'advisor-millet-field': {
    src: '/images/cropx/advisor-millet-field.jpg',
    alt: 'Millet growing in a field, heads formed and drying',
    width: 500,
    height: 500,
    credit: 'pheezy (CC BY)',
    creditUrl: 'https://www.flickr.com/photos/51035644690@N01/16809191290',
    licence: 'CC BY',
  },
  'advisor-planting': {
    src: '/images/cropx/advisor-planting.jpg',
    alt: 'A farmer placing seed into prepared soil by hand',
    width: 1400,
    height: 1400,
    credit: 'Lokalpedia (CC BY-SA)',
    creditUrl: 'https://commons.wikimedia.org/w/index.php?curid=126335173',
    licence: 'CC BY-SA',
  },
  'climate-hero-drought': {
    src: '/images/cropx/climate-hero-drought.jpg',
    alt: 'Bare soil broken into deep cracks by sustained heat and no rain',
    width: 1024,
    height: 683,
    credit: 'Bert Kaufmann (CC BY)',
    creditUrl: 'https://www.flickr.com/photos/22746515@N02/3487433937',
    licence: 'CC BY',
  },
  'climate-rain-clouds': {
    src: '/images/cropx/climate-rain-clouds.jpg',
    alt: 'Heavy rain clouds building over open farmland',
    width: 1024,
    height: 517,
    credit: 'JamesWatkins (CC BY)',
    creditUrl: 'https://www.flickr.com/photos/23737778@N00/7115229223',
    licence: 'CC BY',
  },
  'climate-irrigation': {
    src: '/images/cropx/climate-irrigation.jpg',
    alt: 'Water running along an irrigation channel between cultivated beds',
    width: 1024,
    height: 1024,
    credit: null,
    creditUrl: 'https://www.flickr.com/photos/41284017@N08/31992016837',
    licence: 'Public Domain Mark',
  },
  'climate-sahel': {
    src: '/images/cropx/climate-sahel.jpg',
    alt: 'Sparse semi-arid savanna landscape typical of the Sahel',
    width: 1024,
    height: 576,
    credit: '16:9clue (CC BY)',
    creditUrl: 'https://www.flickr.com/photos/53255320@N07/5312120832',
    licence: 'CC BY',
  },
  'climate-dry-riverbed': {
    src: '/images/cropx/climate-dry-riverbed.jpg',
    alt: 'A river reduced to dry sand and exposed stones',
    width: 1400,
    height: 1400,
    credit: null,
    creditUrl: 'https://wordpress.org/photos/photo/242641ed80/',
    licence: 'CC0 1.0',
  },
  'surveillance-hero-pest': {
    src: '/images/cropx/surveillance-hero-pest.jpg',
    alt: 'Maize leaves torn and windowed by feeding caterpillars',
    width: 1024,
    height: 662,
    credit: 'photofarmer (CC BY)',
    creditUrl: 'https://www.flickr.com/photos/62528187@N00/5843720918',
    licence: 'CC BY',
  },
  'surveillance-leaf-disease': {
    src: '/images/cropx/surveillance-leaf-disease.jpg',
    alt: 'A crop leaf showing the lesions and discolouration of active disease',
    width: 1024,
    height: 1024,
    credit: null,
    creditUrl: 'https://www.flickr.com/photos/62295966@N07/27290852221',
    licence: 'CC0 1.0',
  },
  'surveillance-scouting': {
    src: '/images/cropx/surveillance-scouting.jpg',
    alt: 'A farmer bending into the crop canopy to inspect plants for damage',
    width: 1024,
    height: 1024,
    credit: null,
    creditUrl: 'https://www.flickr.com/photos/41284017@N08/51340755816',
    licence: 'Public Domain Mark',
  },
  'surveillance-phone-field': {
    src: '/images/cropx/surveillance-phone-field.jpg',
    alt: 'A mobile phone being used out in the field beside standing crops',
    width: 1024,
    height: 683,
    credit: null,
    creditUrl: 'https://www.flickr.com/photos/41284017@N08/49392119033',
    licence: 'Public Domain Mark',
  },
  'surveillance-cassava': {
    src: '/images/cropx/surveillance-cassava.jpg',
    alt: 'Cassava plants in the field with their distinctive lobed leaves',
    width: 1400,
    height: 1400,
    credit: null,
    creditUrl: 'https://commons.wikimedia.org/w/index.php?curid=146547871',
    licence: 'CC0 1.0',
  },
  'agronomist-hero-extension': {
    src: '/images/cropx/agronomist-field-laptop.jpg',
    alt: 'CropX cofounder Idokoh Divine Ojochide examining maize with a laptop in a cornfield',
    width: 2000,
    height: 1500,
    credit: null,
    creditUrl: null,
    licence: null,
  },
  'agronomist-training': {
    src: '/images/cropx/agronomist-training.jpg',
    alt: 'Farmers gathered around a demonstration during a field training session',
    width: 1024,
    height: 680,
    credit: 'CGIAR Climate (CC BY)',
    creditUrl: 'https://www.flickr.com/photos/55227776@N04/9417196732',
    licence: 'CC BY',
  },
  'agronomist-soil-test': {
    src: '/images/cropx/agronomist-soil-test.jpg',
    alt: 'A soil sample being analysed in a laboratory',
    width: 500,
    height: 500,
    credit: 'Idaho National Laboratory (CC BY)',
    creditUrl: 'https://www.flickr.com/photos/30369883@N03/4636448856',
    licence: 'CC BY',
  },
  'agronomist-field-demo': {
    src: '/images/cropx/agronomist-field-demo.jpg',
    alt: 'An advisor and farmers examining a crop in a demonstration plot',
    width: 1024,
    height: 576,
    credit: null,
    creditUrl: 'https://www.flickr.com/photos/41284017@N08/15288092801',
    licence: 'Public Domain Mark',
  },
  'about-mosaic-1': {
    src: '/images/cropx/about-mosaic-1.jpg',
    alt: 'Portrait of a farmer on their land',
    width: 736,
    height: 1024,
    credit: 'SkilledAdventurer (CC BY)',
    creditUrl: 'https://www.flickr.com/photos/140589650@N06/26810278358',
    licence: 'CC BY',
  },
  'about-mosaic-2': {
    src: '/images/cropx/about-mosaic-2.jpg',
    alt: 'Women working together on a harvest',
    width: 1024,
    height: 680,
    credit: 'CGIAR Climate (CC BY)',
    creditUrl: 'https://www.flickr.com/photos/55227776@N04/9417196732',
    licence: 'CC BY',
  },
  'about-mosaic-3': {
    src: '/images/cropx/about-mosaic-3.jpg',
    alt: 'Crop research being carried out in a laboratory',
    width: 1024,
    height: 1024,
    credit: 'TheAnimalDay.org (CC BY)',
    creditUrl: 'https://www.flickr.com/photos/75511522@N03/7001952970',
    licence: 'CC BY',
  },
  'about-mosaic-4': {
    src: '/images/cropx/about-mosaic-4.jpg',
    alt: 'A wide field of sorghum ripening under an open sky',
    width: 2000,
    height: 1333,
    credit: 'Tomascastelazo (CC BY-SA)',
    creditUrl: 'https://commons.wikimedia.org/w/index.php?curid=16981067',
    licence: 'CC BY-SA',
  },
  'blog-drought-varieties': {
    src: '/images/cropx/blog-drought-varieties.jpg',
    alt: 'A drought tolerant crop standing in dry conditions',
    width: 1023,
    height: 680,
    credit: 'Macleay Grass Man (CC BY)',
    creditUrl: 'https://www.flickr.com/photos/73840284@N04/8673974271',
    licence: 'CC BY',
  },
  'blog-soil-health': {
    src: '/images/cropx/blog-soil-health.jpg',
    alt: 'Dark, well-structured soil rich in organic matter',
    width: 499,
    height: 386,
    credit: 'dbking (CC BY)',
    creditUrl: 'https://www.flickr.com/photos/65193799@N00/3430679845',
    licence: 'CC BY',
  },
  'blog-planting-calendar': {
    src: '/images/cropx/blog-planting-calendar.jpg',
    alt: 'Seed being sown at the start of the planting season',
    width: 1023,
    height: 680,
    credit: 'Macleay Grass Man (CC BY)',
    creditUrl: 'https://www.flickr.com/photos/73840284@N04/12112675323',
    licence: 'CC BY',
  },
  'blog-armyworm': {
    src: '/images/cropx/blog-armyworm.jpg',
    alt: 'A caterpillar crop pest on a damaged leaf',
    width: 1024,
    height: 556,
    credit: null,
    creditUrl: 'https://www.flickr.com/photos/54563451@N08/15750996370',
    licence: 'Public Domain Mark',
  },
  'blog-seed-systems': {
    src: '/images/cropx/blog-seed-systems.jpg',
    alt: 'Bagged seed stacked ready for distribution',
    width: 1024,
    height: 269,
    credit: null,
    creditUrl: 'https://www.flickr.com/photos/41284017@N08/10740248266',
    licence: 'Public Domain Mark',
  },
  'blog-cowpea-nitrogen': {
    src: '/images/cropx/blog-cowpea-nitrogen.jpg',
    alt: 'Cowpea plants growing in a field',
    width: 1024,
    height: 768,
    credit: 'Macleay Grass Man (CC BY)',
    creditUrl: 'https://www.flickr.com/photos/73840284@N04/10737281175',
    licence: 'CC BY',
  },
  'contact-support': {
    src: '/images/cropx/contact-support.jpg',
    alt: 'A farmer making a call on a mobile phone',
    width: 800,
    height: 533,
    credit: 'US Army Africa (CC BY)',
    creditUrl: 'https://www.flickr.com/photos/36281822@N08/4005668135',
    licence: 'CC BY',
  },
};

export function image(slot: ImageSlot): ManagedImage {
  return images[slot];
}

/** Every image that carries an attribution requirement, for the credits page. */
export const attributedImages = Object.entries(images)
  .filter(([, value]) => value.credit !== null)
  .map(([slot, value]) => ({ slot: slot as ImageSlot, ...value }));
